### ISSUE TITLE
Test segfaults on 32-bit mips architectures

### ISSUE THREAD

**Issue by ghisvail** [Shark-ML/Shark#112]
Build logs for [mips](https://buildd.debian.org/status/fetch.php?pkg=shark&arch=mips&ver=3.1.3%2Bds1-1&stamp=1472866469) and [mipsel](https://buildd.debian.org/status/fetch.php?pkg=shark&arch=mipsel&ver=3.1.3%2Bds1-1&stamp=1472860366).

All errors are segfaults of the form:
`memory access violation at address: 0x????????: non-existent physical address`

**Comment by Ulfgard** [comment]
valgrind gives me 0 errors on my machine. Not sure what i can do about this, i do not have mips/mipsel available

**Comment by ghisvail** [comment]
> valgrind gives me 0 errors on my machine.

Which confirms these memory access violations are `mips` specific. They *usually* come from dereferencing of misaligned pointers to custom structs. mips-like architectures need to be specifically instructed when data structures are packed.

> Not sure what i can do about this

You could help with your knowledge of the codebase. Are there any pieces of code in the library covered by the failing tests which dereference such custom structs as described above? 

> i do not have mips/mipsel available

We (Debian) do, but porters time is pretty limited. It would be desirable to narrow the location of the problem down, so these guys can triage and investigate a fix.

**Comment by Ulfgard** [comment]
I focussed on the BLAS_Vector_Proxy test, because it is probably the most straight forward part, but I came up with nothing. Essentially the code creates an array of doubles (via boost::vector<double> internally) and then performs a few tests whether the subindexing works. I do not see any other point where we actively dereferenciate pointers, but of course there a few structs/classes involved and references (&) which then could end up as pointers being dereferenced. 

I tried to figure out what similarities between the tests are, but the situation is weird, as sometimes a test is failing even though it performs essentially the same operation (e.g. replacing a multiplication by an exp or something like that). I guess it does not always fail, just when you are struck by bad luck.

is it possible to turn off the mips/mipsel build for now? I would not want to waste precious porting time for something that will probably never be used on those platforms...

**Comment by ghisvail** [comment]
Thanks for your quick look at this. We'll probably disable `mips` and `mipsel` for now and let the porters investigate, should they want to.

**Comment by ghisvail** [comment]
Shark has now transitioned to the next release of Debian. Thanks @Ulfgard for your prompt response which helped this happen.

I should also warn you guys that Debian will be entering the freeze period prior to the next stable release sometime soon. So if you guys were planning a new major release (3.2?) and wish to have it available in Debian Stretch, you should consider not delaying it by too much.

**Comment by ghisvail** [comment]
Just a heads-up on this. The solution was found by a Debian MIPS porter and appears to be a workaround for an issue with the compilation toolchain. The resulting patch should probably stay downstream as a result. Closing.
