### ISSUE TITLE
compute and read a prediction

### ISSUE THREAD

**Issue by arthur-leguennec** [Shark-ML/Shark#158]
Hi,

I'm building a random forest to classify points clouds and I don't understand how compute a prediction and how retrieve this value in a `double`. I did this : 
`unsigned int prediction = m_model(input);`
with input a `RealVector` that contains just one input and m_model a `RFClassifier`.
I have an error on m_model that say `no suitable conversion function from "shark::RealVector"`.

Is someone can help me ?

Thanks,
Arthur

**Comment by Ulfgard** [comment]
Hi,

you could help us helping you by giving the complete error message. 

The answer to your problem is that the classifier is returning the probability for each class according to the proportion of trees voting for it. Thus the return value is a vector. To obtain the label you can for example do

unsigned int prediction = arg_max(m_model(input));

**Comment by arthur-leguennec** [comment]
Ok, my issue is resolved. I didn't have run my program because I had some errors in others files but my IDE (Visual Studio) said me there was a problem with that.
Thank you, I close the issue.
