### ISSUE TITLE
Random Forest training is very slow

### ISSUE THREAD

**Issue by TGlas** [Shark-ML/Shark#179]
I have just trained a random forest model with a single tree on a data set with 10000 points and 8192 features. It took 44 minutes on my machine. The same takes 22 seconds with sklearn, that's a factor of 120. I know that the implementation is not really optimized, but this hints at a major inefficiency.

**Comment by TGlas** [comment]
Addendum: memory consumption is also worrying. 655MB is occupied by data, but memory consumption goes up from 1.4GB to about 3.25GB during training. The final model is 38MB on disk, "only" twice that of the sklearn model, which is fine provided the wasteful text-based archive format.

I tried with two trees - still not much of a forest. The runtime seems to be exactly proportional to the number of trees (88 minutes). I.e., it is really 44 minutes per tree, not a costly pre-processing step followed by cheap tree construction, which would have been more acceptable. With two trees, the memory consuption remains the same, and as expected, the model file size doubles.

**Comment by Ulfgard** [comment]
Hi,

memory consumption is not too unexpected. You would expect the consumption to be 
NumThreads * (1-OOBRatio) * DataSize

i think there is some inefficient data copying done on the way. Assuming a split is performed by data copying and not in-place, we would expect consumption to be 

NumThreads * (1-OOBRatio) * DataSize * log(MaxTreeDepth) 

But i have no idea how the current implementation works. It could be that it has never been tried on a problem with so many inputs. NEverhteless, the current implementation is considered to be dead anyways, so we should replace it asap.

**Comment by inglada** [comment]
Hi,

I just made some timing measures using the RF tutorial example (only the training step and using the small C.csv training set) and the current implementation in master is 2x slower than the one from release 3.1.1 (which was already much slower than for instance OpenCV's).

The current code seems more complex than the one from 3.1.1. You say that the current implementation is dead. Are there any plans to work on it in the near future?

Thanks.

**Comment by inglada** [comment]
Just to give some context, we recently integrated Shark in Orfeo Toolbox (remote sensing image processing) where we already encapsulate the ML module from OpenCV and aso libsvm. Our goal was to be able to do parallel learning, since the other libs can't do that. The use of data batches was also appealing for us. For a quick overview of our rationale, you can have a look at https://www.orfeo-toolbox.org/packages/doc/UserDays2016/shark.pdf.
We are very happy with k-means and autoencoders (ongoing work), but disappointed with the performances of RFTrainer (although classification results are sometimes more accurate than with OpenCV's RF).

Now we are deploying our tools on a HPC cluster were we have to allocate RAM and processing time, and Shark's RF is not usable because of the memory overhead and processing time.

I don't think we have the skills to help with the implementation, but we are happy to test with the huge amounts of data we use for our processing (millions of samples with hundreds of dimensions and up to 20 classes).

**Comment by Ulfgard** [comment]
Hi,

we currently have a new implementation, which is however awaiting scientific review and integration into shark. It is known to have state-of-the-art performance, especially in the HPC area. However this scientific process takes time and the author does not want it to be integrated before this is done.

All that remains until then is to sift through the implementation and try to make it a little faster. I think when the current implementation was benchmarked it was done with only a small amount of features. This might explain much of the differences we see. There also seems to be a memory problem in the current implementation(not a leak but suboptimal use of memory).

**Comment by Ulfgard** [comment]
fixed by introduction of new implementation of Random Forest
