### ISSUE TITLE
Container is Not Independent????

### ISSUE THREAD

**Issue by Electric-Turtle** [Shark-ML/Shark#203]
I have created a shark::CARTTrainer object. When I call the "train" method on a CARTClassifier<RealVector> and a shark::RegressionDataset that I initialized with a call to shark::createLabeledDataFromRange, I get the following error:

terminate called after throwing an instance of 'shark::Exception'
  what():  [/home/trent/git_repos/Shark/include/shark/Data/Impl/Dataset.inl::repartition,350] Container is not Independent
Aborted (core dumped)

Code snippet:
```
  shark::RegressionDataset data = shark::createLabeledDataFromRange(inputs,labels);
  data.makeIndependent();
  trainer_.train(model_, data);
```
Any idea why this would happen?

**Comment by Ulfgard** [comment]
Hi,

found this bug two days ago as well. We are currently completely rewriting the tree classes so i postponed the fix. Note that this means that noone has used the CARTTrainer in a long time and someone has forgotten to add a test-case. I would advice to use the RFClassifier instead. It might be that I am going to remove this class just because of the fact that noone used it, ever. Would you agree or do you really need a pruned decision tree?

**Comment by Ulfgard** [comment]
removed CART.

**Comment by Electric-Turtle** [comment]
After the fact, but yes Random Forests will work. Glad to know it wasn't just me who couldn't get the CART module to run :)

**Comment by Ulfgard** [comment]
great. please pull the latest master before using the Random Forest, there are some speed gains there to be had :)
