### ISSUE TITLE
Unresolved externals whist using the LinearRegressionTutorial example

### ISSUE THREAD

**Issue by imamushroom** [Shark-ML/Shark#207]
I am unable to compile the LinearRegressionTutorial example using the shark library that I have already built and installed with apparent success. I used a git clone to pull the current master.

There is a shark.lib file in the lib directory for the shark folder and my project linker is pointing to this directory, as well as the boost lib directory (x86 version only as I need a Win32 app). Windows is 64bit.

The unresolved externals are listed below:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: virtual void __thiscall shark::LinearRegression::train(class shark::LinearModel<class remora::vector<double,struct remora::cpu_tag> > &,class shark::LabeledData<class remora::vector<double,struct remora::cpu_tag>,class remora::vector<double,struct remora::cpu_tag> > const &)" (?train@LinearRegression@shark@@UAEXAAV?$LinearModel@V?$vector@NUcpu_tag@remora@@@remora@@@2@ABV?$LabeledData@V?$vector@NUcpu_tag@remora@@@remora@@V12@@2@@Z)	SharkStdevTest	C:\Users\ypx7647\source\repos\SharkStdevTest\SharkStdevTest\SharkStdevTest.obj	1	
Error	LNK2001	unresolved external symbol "public: __thiscall shark::LinearRegression::LinearRegression(double)" (??0LinearRegression@shark@@QAE@N@Z)	SharkStdevTest	C:\Users\ypx7647\source\repos\SharkStdevTest\SharkStdevTest\SharkStdevTest.obj	1	
Error	LNK2001	unresolved external symbol "void __cdecl shark::csvStringToData(class shark::Data<class remora::vector<double,struct remora::cpu_tag> > &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,char,char,unsigned int)" (?csvStringToData@shark@@YAXAAV?$Data@V?$vector@NUcpu_tag@remora@@@remora@@@1@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@DDI@Z)	SharkStdevTest	C:\Users\ypx7647\source\repos\SharkStdevTest\SharkStdevTest\SharkStdevTest.obj	1	
Error	LNK2001	unresolved external symbol "class std::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253> shark::random::globalRng" (?globalRng@random@shark@@3V?$mersenne_twister_engine@I$0CA@$0CHA@$0BIN@$0BP@$0JJAILANP@$0L@$0PPPPPPPP@$06$0JNCMFGIA@$0P@$0OPMGAAAA@$0BC@$0GMAHIJGF@@std@@A)	SharkStdevTest	C:\Users\ypx7647\source\repos\SharkStdevTest\SharkStdevTest\SharkStdevTest.obj	1	
`

The cmake file I used to compile the shark library is below:
![image](https://user-images.githubusercontent.com/7989372/32917182-a9349794-cb1e-11e7-95b5-276b28bd8b59.png)

Clearly, the tutorial files should compile cleanly so I assume this is a bug. If not, what am I doing wrong?

The example project log file is here:
[SharkStdevTest.log](https://github.com/Shark-ML/Shark/files/1482625/SharkStdevTest.log)

Thanks in advance.

**Comment by Ulfgard** [comment]
There is unfortunately a bit of information missing.

I see different paths in your screenshot and your reported error message.
Is this an error when you build the shark project (e.g. BUILD_ALL) or is this an error when you try to compile your own program using the shark library? If it is a bug during compilation of your own project, it is _very_ likely a bug in your setup because all examples are by default build during compilation of shark.

If it happened during compilation of shark, have you tried using the current master? last time i checked appveyor, it build alright

if it happened during compilation of your own project, we would strongly advise using the CMakeLists.txt we provide for compiling your own projects (/examples/ExampleProject/CMakeLists.txt). Only if that works you should be trying to build it on your own. In your case i am not sure whether the lirbary is linked at all. printing the actual command line used by your compiler might help. (not sure how to do this in VS, though)

**Comment by imamushroom** [comment]
Sorry about missing the information off. I've updated my original post with the appropriate information.

I'll do as you say and try the examples/ExampleProject/CMakeLists.txt file to see if I can get that working and report back. Thanks for the info.

**Comment by Ulfgard** [comment]
A quick check for your linker command tells me that you forgot to actually link to the shark library. It is not enough to set the linker path, you also have to specify the library to link to.

**Comment by Ulfgard** [comment]
i think this is resolved
