### ISSUE TITLE
Compiling Shark on Ubuntu 17.10

### ISSUE THREAD

**Issue by skrypnyuk** [Shark-ML/Shark#214]
I had some issues recently installing Shark on Ubuntu 17.10. This is how I solved them:
1. I have used github clone code
2. Added the flag to find boost libraries (this is mentioned in the documentation, but just for completeness):
cmake . -DBOOST_LIBRARYDIR=/usr/lib/x86_64-linux-gnu/
3. make fails on Test subdirectory, so I have commented out the following rows in CMakeLists.txt

Enable Testing
include(CTest)
if(BUILD_TESTING)
	enable_testing()
	add_subdirectory( Test )
endif()

Hope it might help someone ;-)

**Comment by Ulfgard** [comment]
what exactly fails?
you could disable tests simply using another flag:

-DBUILD_TESTING=OFF
________________________________

**Comment by skrypnyuk** [comment]
[ 39%] Linking CXX executable ../bin/RBM_ExactGradientTraining
CMakeFiles/RBM_ExactGradientTraining.dir/RBM/ExactGradientTraining.cpp.o: In function `_GLOBAL__sub_I__Z14init_unit_testv':
ExactGradientTraining.cpp:(.text.startup+0xf3): undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)'
collect2: error: ld returned 1 exit status
Test/CMakeFiles/RBM_ExactGradientTraining.dir/build.make:104: recipe for target 'bin/RBM_ExactGradientTraining' failed
make[2]: *** [bin/RBM_ExactGradientTraining] Error 1
CMakeFiles/Makefile2:3914: recipe for target 'Test/CMakeFiles/RBM_ExactGradientTraining.dir/all' failed
make[1]: *** [Test/CMakeFiles/RBM_ExactGradientTraining.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Ulfgard** [comment]
Hi,

even extensive researching didn't help me with this issue. Because apparently, the library itself is found (otherwise we would got more undefined references). So it can only be a C++11 issue as the ABI was changed. This is something we can not fix unfortunately, one can only figure out what works.

For example this guy here:
https://stackoverflow.com/questions/32453386/how-to-compile-boost-unit-test-module-with-clang
Had the issue that he used clang for compilation while boost was compiled with gcc. But that was 15.10, maybe that got fixed in the meantime.
