### ISSUE TITLE
Consider a new release

### ISSUE THREAD

**Issue by inglada** [Shark-ML/Shark#231]
Hi,
Shark's last release dates back a long ago. Could it be possible to tagging current master as a release?
This would allow OTB's debian package to use a recent version of Shark. 
The lack of a recent Shark release is causing issues for the acceptance in debian (https://gitlab.orfeo-toolbox.org/orfeotoolbox/otb/issues/1592).
Thanks

**Comment by Ulfgard** [comment]
Hi, 

Give me until Sunday to check code and documentation. It is probably going to be shark 4.0

**Comment by Ulfgard** [comment]
I am not sure i cna make Sunday. I spent a lot of time on updating the docs but they are still in a rough shale (but at least they should now be usable). I have to fix the problem that i now need to bundle doxylink to build the docs (otherwise debian will not be happy as i had to apply a patch to support doxygen groups).

Also i have to go through every single tutorial and check whether it is lying...

**Comment by Ulfgard** [comment]
docu is progressing. we now ship doxylink together with shark and it seems to work.

 @TGlas volunteered to read through the docu. I am still writing stuff, though.

i have to fix the build script to ensure that we can enable blas properly on most systems.

afterwards we can call it a release.

**Comment by Ulfgard** [comment]
build scripts fixed. version bumped to 4.0.0

**Comment by inglada** [comment]
Nice. Thanks.

**Comment by Ulfgard** [comment]
no docu is still debated

**Comment by Ulfgard** [comment]
done. I close this, i guess we will hear from debian soon rgarding package creation
