### ISSUE TITLE
Sigmoid Kernel

### ISSUE THREAD

**Issue by John1911603424** [Shark-ML/Shark#255]
Hi,do you know where sigmoid kernel is? I didn't find it.

**Comment by Ulfgard** [comment]
We have not implemented it.

**Comment by Ulfgard** [comment]
a longer reply: in our personale xperience, the sigmoid kernel rarely makes sense. It is slightly difficult to work with because positive-definiteness of the kernel is not guaranteed. Also as a model the sigmoid kernel has _super weird_ behaviour.

See here:

https://cloud.githubusercontent.com/assets/5733246/18803657/6883294a-81c8-11e6-8950-6989e765966a.png

**Comment by John1911603424** [comment]
Thanks.
