### ISSUE TITLE
Fundamental Matrix structure

### ISSUE THREAD

**Issue by skn123** [Shark-ML/Shark#6]
In order to start work on adding Eigen / ViennaCl support to Shark, I would need to change the basic Matrix structure. Can someone point out what would be the best place to begin this?

**Comment by Ulfgard** [comment]
Hi,

This is a tough one. I think there is exactly zero chance of incorporating Eigen into shark::blas as the interfaces are completely incompatible. It would probably be easier to rewrite shark as a whole to use Eigen instead of trying to push eigen into blas.

For ViennaCL the situation is *slightly* better. ViennaCL was designed to fit the boost::ublas interface. This is good as shark::blas is basically a fork of a subset of boost::ublas (do not ask me why, this would result in a long and tiring rant). I am not sure what the current state of compatibility is as the boost development branch and shark::blas diverged from the point of fork so it is not 100% compatible any more. I am positive that very basic expressions are still compatible and for the rest one might need fixes.

The issue is, however, that just optionally replacing the shark::blas implementation by ViennaCL is not going to give good performance as shark itself is not well structured for GPU support yet. However, if the goal is to extend shark::blas by a gpu part (e.g. by adding a gpu_vector and matrix class etc) using viennaCL a a backend mfor the computations might be a good idea. In the next step one could then try to give shark more gpu support, as we are currently trying to do with convolutional neural networks.


When it comes to blas development, I have a few plans in the drawer which are going to improve things a lot.

**Comment by skn123** [comment]
@Ulfgard I think you have answered my question. The intention of using ViennaCL would be to speed up sparse/dense Linear algebra routines. The second aspect of making algorithms compatible with OpenCL would come in naturally.

**Comment by Ulfgard** [comment]
I thought a bit about that and skimmed a bit through the viennacl documentation and I think this might actually be possible. It will take some time as i have to ensure that all required operations of our blas are there and I need to write some glue-code between our types and their types.

The goal would be that in the end exchanging the types would put the code on the GPU as to make use of the template system of shark.

I put Milestone 3.1 on it, but that might change
